<a href="https://colab.research.google.com/github/AnneKathrinHuber/Data-Science---Entrega-1---Anne-Kathrin-Huber/blob/main/Notebook_5_Anne_Kathrin_Huber.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

    1. Crear un arreglo de ceros de longitud 12.
    2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5.
    3. Crear un arreglo que tenga los números del 10 al 49.
    4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8.
    5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.
    6. Calcular la media de un arreglo usando np.sum.
    7. Calcular la varianza de un arreglo usando np.sum y np.mean.
    8. Crear un array de números aleatorios usando np.random.randn.


1. Crear un arreglo de ceros de longitud 12.

In [ ]:
# Importar librería
import numpy as np

In [ ]:
# Crear un arreglo de ceros de longitud 12
arreglo_1 = np.zeros(12)

# Mostrar arreglo en pantalla
print(arreglo_1)

# Mostrar longitud del arreglo
len (arreglo_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5.

In [ ]:
# Crear un arreglo de ceros de longitud 10
arreglo_2 = np.zeros(10)

# Asignar un 10 en la posición número 5 (índice 4, porque se empieza desde 0)
arreglo_2[4] = 10

# Mostrar arreglo en pantalla
print(arreglo_2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49.

In [ ]:
# Crear un arreglo con los números del 10 al 49
arreglo_3 = np.arange(10, 50)

# Mostrar arreglo en pantalla
print(arreglo_3)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8.

In [ ]:
# Crear un arreglo 2D de shape (3, 3) con los números del 0 al 8
arreglo_4 = np.arange(9).reshape((3, 3))

# Mostrar arreglo en pantalla
print(arreglo_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.

In [ ]:
# Crear un arreglo de 100 números aleatorios
arreglo_5 = np.random.rand(100)

# Calcular la media
media = np.mean(arreglo_5)

# Calcular la varianza
varianza = np.var(arreglo_5)

# Mostrar arreglo en pantalla
print(arreglo_5)
# Mostrar media en pantalla
print("Media:", media)
# Mostrar varianza en pantalla
print("Varianza:", varianza)

[0.12255273 0.42792704 0.17564104 0.77696326 0.66256968 0.40536612
 0.24050036 0.637751   0.19093904 0.96125967 0.56404405 0.09823364
 0.43027643 0.6282848  0.64707157 0.93164517 0.26206558 0.39317799
 0.90518833 0.94993224 0.42135491 0.22914503 0.67418889 0.01688586
 0.60590304 0.65801133 0.07773476 0.53969457 0.62013654 0.32387662
 0.71060329 0.22029056 0.62789936 0.63228645 0.71600594 0.6483821
 0.36483226 0.67397406 0.2261972  0.46089768 0.44518866 0.55894724
 0.33051327 0.15753991 0.44716284 0.92007433 0.28095191 0.34212893
 0.44719856 0.62346912 0.26047778 0.33855904 0.80755899 0.68450376
 0.71500521 0.75316421 0.87029563 0.93482811 0.52818314 0.77674477
 0.44305706 0.69043521 0.12288972 0.39361288 0.54833662 0.25380164
 0.81862048 0.44283445 0.28307948 0.70965954 0.43509136 0.31814342
 0.4479322  0.20176822 0.9769412  0.62048206 0.09263164 0.33200269
 0.35953472 0.67062216 0.38822545 0.61449593 0.07921239 0.74875704
 0.81172989 0.40242059 0.51688118 0.6789399  0.38890854 0.27342

6. Calcular la media de un arreglo usando np.sum.

In [ ]:
# Crear un arreglo
arreglo_6 = np.array([1, 20, 3, 45, 83])

# Calcular la media usando np.sum
media = np.sum(arreglo_6) / len(arreglo_6)

# Mostrar arreglo en pantalla
print("Arreglo:", arreglo_6)
# Mostrar media en pantalla
print("Media:", media)


Arreglo: [ 1 20  3 45 83]
Media: 30.4


7. Calcular la varianza de un arreglo usando np.sum y np.mean.

In [ ]:
# Crear un arreglo
arreglo_7 = np.array([56, 77, 30, 34, 5])

# Calcular la media
media = np.mean(arreglo_7)

# Calcular la varianza manualmente
varianza = np.sum((arreglo_7 - media) ** 2) / len(arreglo_7)

# Mostrar arreglo en pantalla
print("Arreglo:", arreglo_7)
# Mostrar media en pantalla
print("Media:", media)
# Mostrar varianza en pantalla
print("Varianza:", varianza)


Arreglo: [56 77 30 34  5]
Media: 40.4
Varianza: 597.0400000000001


8. Crear un array de números aleatorios usando np.random.randn.

In [ ]:
# Crear un arreglo de números aleatorios
arreglo_8 = np.random.randn(100)

# Mostrar arreglo en pantalla
print(arreglo_8)


[-0.02151143  0.0117079  -0.90567238  0.88072236  1.83063873  0.89502826
  0.24210253 -1.07410603  1.52808284  0.90012415 -0.82935935  0.51085591
  1.18833059  0.10031962  0.52255462 -0.09568813 -0.36674047  0.36241846
 -0.59429673  1.58374827 -0.90024611 -1.06132255 -0.58402538  0.22678481
 -0.44826158  2.602523   -0.64160075 -3.04799319  0.44158112  0.7809783
  0.12451828  0.15598038 -0.46147038 -1.50387418  0.3328394   0.00788862
 -0.28937061  0.45311117 -0.57370258 -0.76224838  0.63613096 -0.52005194
 -0.61004865 -0.44605299 -0.94600848 -0.39039911  0.9349617   0.17929293
 -0.53645309  0.76374125  1.67576821 -0.33672472  0.81619129 -0.26682892
  0.21474024  1.68349026  0.491333   -0.12971072  0.27908026  0.37381676
  0.28938113  0.31190085 -1.32186149 -1.22127095  0.77115346  1.25672943
  0.35203471  1.06392453  1.03001523  1.20781766  0.17889877  1.47979641
 -1.07786939 -0.77272922 -0.46024494 -0.86983108 -0.1599759  -0.95670499
 -0.30461279  1.48892199  0.98185254  0.77650697  0.

########